
[workspace]
members = [
  "cmf",
  "proj/cargo/rs_hello",
  "proj/cargo/rs_hello_io",
]

[package]
name = "cargo"
version = "0.1.0"
edition = "2021"
default-run = "_"

[[bin]]
name = "_"
path = "src/bin/_.rs"

[lib]
name = "rs_lib"
path = "src/lib/_.rs"
